### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by alendit** [amplab/benchmark#8]
Hi,

my Name is Dimitri Vorona and I am from the Technische Universität in Munich. 

We'd like to reuse your deployment code (with appropriate credits, of course), yet, can not do it for the apparent lack of licencing.

If you don't have any objections for the code to be reused, I'd be very thankful, if you'd explicitly specify a licence somewhere.

**Comment by pwendell** [comment]
I've added an Apache license to the code. Thanks for bringing this up.
